version: '3.3'

services:
  redis_over_http:
    build: .
    ports:
      - "8117:80"
    env_file:
      - .env 
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:10.0.0.210"
    restart: always
